"use client";

import { useState } from "react";
import { addHealthRecord } from "@/lib/data";

interface AddHealthModalProps {
    cattle: { rfid: string; cattleName: string };
    onClose: () => void;
    onSuccess: () => void;
}

export default function AddHealthModal({ cattle, onClose, onSuccess }: AddHealthModalProps) {
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState("");

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSubmitting(true);
        setError("");

        const formData = new FormData(e.currentTarget as HTMLFormElement);
        const record = {
            id: "", // Generated by backend
            timestamp: new Date().toISOString(),
            rfid: cattle.rfid,
            cattleName: cattle.cattleName,
            temperature: parseFloat(formData.get("temperature") as string),
            heartRate: parseInt(formData.get("heartRate") as string),
            respiratoryRate: parseInt(formData.get("respiratoryRate") as string),
            healthStatus: formData.get("healthStatus") as any,
            riskLevel: formData.get("riskLevel") as any,
            diagnosis: formData.get("diagnosis") as string,
            treatment: formData.get("treatment") as string,
            notes: formData.get("notes") as string,
            recordedBy: localStorage.getItem("username") || "Vet"
        };

        try {
            const result = await addHealthRecord(record);
            if (result.success) {
                onSuccess();
            } else {
                setError(result.message);
            }
        } catch (err) {
            setError("Failed to add record");
        }
        setSubmitting(false);
    };

    return (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-fade-in-up">
                {/* Header */}
                <div className="bg-gradient-to-r from-teal-600 to-emerald-600 p-6 text-white flex justify-between items-center">
                    <h3 className="text-xl font-bold flex items-center">
                        <span className="text-2xl mr-2">🩺</span>
                        Add Health Check
                    </h3>
                    <button onClick={onClose} className="text-white/80 hover:text-white text-2xl">×</button>
                </div>

                {/* Body */}
                <div className="p-6 max-h-[80vh] overflow-y-auto">
                    <div className="mb-6 bg-emerald-50 p-4 rounded-xl border border-emerald-100">
                        <p className="text-sm text-gray-500">Patient</p>
                        <p className="font-bold text-gray-800 text-lg">{cattle.cattleName}</p>
                        <p className="text-xs text-gray-500 font-mono">{cattle.rfid}</p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-1">Status</label>
                                <select name="healthStatus" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none">
                                    <option value="Healthy">Healthy</option>
                                    <option value="Under Observation">Under Observation</option>
                                    <option value="Sick">Sick</option>
                                    <option value="Critical">Critical</option>
                                </select>
                            </div>
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-1">Risk Level</label>
                                <select name="riskLevel" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none">
                                    <option value="Low">Low</option>
                                    <option value="Medium">Medium</option>
                                    <option value="High">High</option>
                                    <option value="Critical">Critical</option>
                                </select>
                            </div>
                        </div>

                        <div className="grid grid-cols-3 gap-3">
                            <div>
                                <label className="block text-xs font-semibold text-gray-700 mb-1">Temp (°C)</label>
                                <input type="number" step="0.1" name="temperature" defaultValue="38.5" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none" />
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-gray-700 mb-1">Heart (bpm)</label>
                                <input type="number" name="heartRate" defaultValue="65" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none" />
                            </div>
                            <div>
                                <label className="block text-xs font-semibold text-gray-700 mb-1">Resp (bpm)</label>
                                <input type="number" name="respiratoryRate" defaultValue="25" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none" />
                            </div>
                        </div>

                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-1">Diagnosis</label>
                            <input type="text" name="diagnosis" placeholder="e.g. Routine Checkup" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none" />
                        </div>

                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-1">Treatment / Prescription</label>
                            <input type="text" name="treatment" placeholder="e.g. None" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none" />
                        </div>

                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-1">Notes</label>
                            <textarea name="notes" rows={2} className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-emerald-500 outline-none"></textarea>
                        </div>

                        {error && <p className="text-red-500 text-sm text-center bg-red-50 p-2 rounded">{error}</p>}

                        <div className="flex gap-3 pt-2">
                            <button type="button" onClick={onClose} className="flex-1 py-3 text-gray-600 font-semibold hover:bg-gray-100 rounded-xl transition-colors">Cancel</button>
                            <button type="submit" disabled={submitting} className="flex-1 py-3 bg-emerald-600 text-white font-bold rounded-xl hover:bg-emerald-700 transition-colors shadow-lg disabled:opacity-50">
                                {submitting ? "Saving..." : "Save Record"}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
}
