"use client";

import { useState } from "react";
import { addMilkRecord } from "@/lib/data";

interface AddMilkModalProps {
    cattle: { rfid: string; cattleName: string };
    onClose: () => void;
    onSuccess: () => void;
}

export default function AddMilkModal({ cattle, onClose, onSuccess }: AddMilkModalProps) {
    const [submitting, setSubmitting] = useState(false);
    const [error, setError] = useState("");

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setSubmitting(true);
        setError("");

        const formData = new FormData(e.currentTarget as HTMLFormElement);
        const record = {
            id: "", // Generated by backend
            timestamp: new Date().toISOString(),
            rfid: cattle.rfid,
            cattleName: cattle.cattleName,
            quantity: parseFloat(formData.get("quantity") as string),
            quality: formData.get("quality") as any,
            temperature: parseFloat(formData.get("temperature") as string),
            session: formData.get("session") as any,
            recordedBy: localStorage.getItem("username") || "Farmer"
        };

        try {
            const result = await addMilkRecord(record);
            if (result.success) {
                onSuccess();
            } else {
                setError(result.message);
            }
        } catch (err) {
            setError("Failed to add record");
        }
        setSubmitting(false);
    };

    return (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
            <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-fade-in-up">
                {/* Header */}
                <div className="bg-gradient-to-r from-blue-600 to-indigo-600 p-6 text-white flex justify-between items-center">
                    <h3 className="text-xl font-bold flex items-center">
                        <span className="text-2xl mr-2">🥛</span>
                        Add Milk Record
                    </h3>
                    <button onClick={onClose} className="text-white/80 hover:text-white text-2xl">×</button>
                </div>

                {/* Body */}
                <div className="p-6">
                    <div className="mb-6 bg-blue-50 p-4 rounded-xl border border-blue-100">
                        <p className="text-sm text-gray-500">Cattle</p>
                        <p className="font-bold text-gray-800 text-lg">{cattle.cattleName}</p>
                        <p className="text-xs text-gray-500 font-mono">{cattle.rfid}</p>
                    </div>

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-1">Quantity (L)</label>
                                <input type="number" step="0.1" name="quantity" required className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" placeholder="12.5" />
                            </div>
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-1">Quality</label>
                                <select name="quality" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none">
                                    <option value="Excellent">Excellent</option>
                                    <option value="Good">Good</option>
                                    <option value="Fair">Fair</option>
                                    <option value="Poor">Poor</option>
                                </select>
                            </div>
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-1">Temp (°C)</label>
                                <input type="number" step="0.1" name="temperature" defaultValue="37.5" required className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
                            </div>
                            <div>
                                <label className="block text-sm font-semibold text-gray-700 mb-1">Session</label>
                                <select name="session" className="w-full px-3 py-2 border rounded-lg focus:ring-2 focus:ring-blue-500 outline-none">
                                    <option value="Morning">Morning</option>
                                    <option value="Evening">Evening</option>
                                </select>
                            </div>
                        </div>

                        {error && <p className="text-red-500 text-sm text-center bg-red-50 p-2 rounded">{error}</p>}

                        <div className="flex gap-3 pt-2">
                            <button type="button" onClick={onClose} className="flex-1 py-3 text-gray-600 font-semibold hover:bg-gray-100 rounded-xl transition-colors">Cancel</button>
                            <button type="submit" disabled={submitting} className="flex-1 py-3 bg-blue-600 text-white font-bold rounded-xl hover:bg-blue-700 transition-colors shadow-lg disabled:opacity-50">
                                {submitting ? "Saving..." : "Save Record"}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
}
